### ISSUE TITLE
Kickoff Todo

### ISSUE THREAD

**Issue by fruzyna** [wildstang/robot_framework#15]
We should have a bunch of software to update come kickoff, some of these can be automatically updated via the wizard:

- [x] `/vendordeps`
- [x] WPILib plugin from https://github.com/wpilibsuite/vscode-wpilib/releases/latest
- [x] `edu.wpi.first.GradleRIO` version in `build.gradle`
- [x] `projectYear` in `/.wpilib/wpilib_preferences.json`
- [x] `frcYear` in `/settings.gradle`
